# ASSIGNMENT - 6 - MACHINE LEARNING LAB
### NAME - PULKIT JASTI
### ROLL NUMBER - AP19110010491
### CSE - C

Implement a Naïve Bayes classifier for the IRIS dataset and evaluate the classification
performance. Draw the confusion matrix, compute accuracy, error, and other measures as
applicable.

In [3]:
# load the iris dataset
import numpy as np
from math import sqrt
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import metrics
iris = load_iris()
# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target
# splitting X and y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
# training the model on training set
gnb = GaussianNB()
gnb.fit(X_train, y_train)
# making predictions on the testing set
y_pred = gnb.predict(X_test)
# comparing actual response values (y_test) with predicted response values (y_pred)
print("Confusion Matrix : ")
print(confusion_matrix(y_test, y_pred))
print("\nGaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
# 1. RMSE: Root Mean Squared Error
# 2. MAE: Mean Absolute Error
# 3. R-Squared Error
y_mean = np.mean(y)
rmse_nume = 0
mae_nume = 0
n = len(y_pred)
for i in y:
    j = 0
    if(j<n):
        rmse_nume += (i - y_pred[j])**2
        mae_nume += abs(i - y_pred[j])
        j = j+1
SSR = 0
SST = 0
for i in y:
    j = 0
    SST += (i-y_mean)**2
    if(j<n):
        SSR += (y_pred[j]-y_mean)**2
        j = j+1
R_Squared = SSR/SST
rmse = pow(rmse_nume/n,1/2)
mae = mae_nume/n
print("\nRoot Mean Squared Error for the given data is ", rmse)
print("\nMean Absolute Error for the given data is ",mae)
print("\nR-Squared for the given data is ",R_Squared)
print("\nClassification Report : ")
print(classification_report(y_test, y_pred))

Confusion Matrix : 
[[19  0  0]
 [ 0 19  2]
 [ 0  1 19]]

Gaussian Naive Bayes model accuracy(in %): 95.0

Root Mean Squared Error for the given data is  2.041241452319315

Mean Absolute Error for the given data is  2.5

R-Squared for the given data is  1.5

Classification Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.95      0.90      0.93        21
           2       0.90      0.95      0.93        20

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

